@echo off
set "GOROOT=d:/code/DevTools/go"
set "PATH=d:/code/DevTools/go/bin;%PATH%"
set "SERVER_PORT=8080"
set "SERVER_MODE=debug"
set "EXTERNAL_API_URL=http://101.201.37.86:8501/"
set "EXTERNAL_API_TIMEOUT=5s"
set "MAX_RETRIES=3"
set "MEMORY_CACHE_SIZE=1000"
set "MEMORY_CACHE_TTL=5m"
set "REDIS_ADDR="
set "REDIS_PASSWORD="
set "REDIS_DB=0"
set "REDIS_CACHE_TTL=30m"
set "RATE_LIMIT=100"
set "RATE_BURST=200"
set "ENABLE_AUTH=false"
set "JWT_SECRET=your-secret-key-change-in-production"
cd /d "d:/code/Moshi_Chanlun_Draw_Lines/kline-indicator-service"
server.exe
